/*
 * File: Scripts/AM/store/SpreadsheetStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.store.SpreadsheetStore', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'AM.model.SpreadsheetModel'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      autoLoad: false,
      storeId: 'SpreadsheetTreeStore',
      model: 'AM.model.SpreadsheetModel',
      root: {
        expanded: true,
        text: 'WorkBook',
        icon: 'Content/img/excel.png',
        type: 'ExcelWorkbookNode'
      },
      proxy: {
        type: 'ajax',
        actionMethods: {
          read: 'POST'
        },
        extraParams: {
          type: 'ExcelWorkbookNode',
          context: null,
          endpoint: null,
          baseurl: null
        },
        timeout: 600000,
        url: 'spreadsheet/getnode',
        reader: {
          type: 'json'
        }
      }
    }, cfg)]);
  }
});