/*
 * File: Scripts/AM/view/search/SearchCombo.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.search.SearchCombo', {
  extend: 'Ext.form.field.ComboBox',
  alias: 'widget.searchcombo',

  width: 90,
  value: 50,
  fieldLabel: 'Limit',
  labelWidth: 40,
  displayField: 'name',
  forceSelection: false,
  store: 'SearchCmbStore',
  valueField: 'value',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      listeners: {
        beforerender: {
          fn: me.onComboboxBeforeRender,
          scope: me
        }
      }
    });

    me.callParent(arguments);
  },

  onComboboxBeforeRender: function(abstractcomponent, options) {
    abstractcomponent.getStore().load();
  }

});