/*
 * File: Scripts/AM/view/AMViewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.AMViewport', {
  extend: 'Ext.container.Viewport',

  requires: [
    'AM.view.directory.DirectoryPanel',
    'AM.view.common.CenterPanel'
  ],

  layout: {
    type: 'border'
  },

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'container',
          region: 'north',
          height: 55,
          html: '<div id="header" class="exchangeBanner"><span style="float: left"><img alt="q" src="Content/img/iRINGTools_logo.png" style="margin: 0 0 0 11px; vertical-align: -20%" /><span style="margin: 0 0 0 6px;"><font size="5px" style="font-family: Arial, Helvetica, Sans-Serif">Adapter Manager</font></span> </span><span style="float: right; margin: 18px 36px 1px 0"><a href="http://iringug.org/wiki/index.php?title=IRINGTools" target="_blank" class="headerLnkBlack">Help</a>&nbsp;&nbsp;&nbsp;&nbsp;<a id="about-link" href="#" class="headerLnkBlack">About</a></span></div>'
        },
        {
          xtype: 'directorypanel',
          region: 'west'
        },
        {
          xtype: 'centerpanel',
          region: 'center'
        }
      ]
    });

    me.callParent(arguments);
  }

});