USE [XYZ]

--SELECT 'INSERT INTO [LINES] VALUES ('''+ISNULL([TAG],'')+''','''+ISNULL([ID],'')+''','''+ISNULL([AREA],'')+''','''+ISNULL([TRAINNUMBER],'')+''','''+ISNULL([SPEC],'')+''','''+ISNULL([SYSTEM],'')+''','''+ISNULL([LINENO],'')+''','''+ISNULL([NOMDIAMETER],'')+''','''+ISNULL([INSULATIONTYPE],'')+''','''+ISNULL([HTRACED],'')+''','''+ISNULL([CONSTTYPE],'')+''','''+ISNULL([DESPRESSURE],'')+''','''+ISNULL([TESTPRESSURE],'')+''','''+ISNULL([PWHT],'')+''','''+ISNULL([TESTMEDIA],'')+''','''+ISNULL([MATLTYPE],'')+''','''+ISNULL([NDT],'')+''','''+ISNULL([NDE],'')+''','''+ISNULL([PIPECLASS],'')+''','''+ISNULL([PIDNUMBER],'')+''','''+ISNULL([DESTEMPERATURE],'')+''','''+ISNULL([PAINTSYSTEM],'')+''','''+ISNULL([DESIGNCODE],'')+''','''+ISNULL([COLOURCODE],'')+''','''+ISNULL([EWP],'')+''','''+ISNULL([USER1],'')+''','''+ISNULL([TAGSTATUS],'')+''','''+ISNULL([FULLLINE],'')+''','''+ISNULL([UOM_NOMDIAMETER],'')+''','''+ISNULL([UOM_DESPRESSURE],'')+''','''+ISNULL([UOM_DESTEMPERATURE],'')+''')' FROM [LINES]
DELETE FROM [LINES]
INSERT INTO [LINES] VALUES ('90009-O','0100000041','90','','AAB3','O','009','150','IP','','NEW','5.2','','','','','','','','','160','','','','***','','NEW','90-O-009','mm','kPag','Deg C')
INSERT INTO [LINES] VALUES ('90010-O','0100000039','91','','AAB3','O','010','80','IH','','NEW','5.2','','','','','','','','90-AO5676','163','','','','***','','NEW','90-O-010','mm','kPag','Deg C')

--SELECT 'INSERT INTO [VALVES] VALUES ('''+ISNULL([KEYTAG],'')+''','''+ISNULL([TAG_NO],'')+''','''+ISNULL([VAREA],'')+''','''+ISNULL([VTYP],'')+''','''+ISNULL([VTRAIN],'')+''','''+ISNULL([VNUM],'')+''','''+ISNULL([VSUFFIX],'')+''','''+ISNULL([TAG_TYPE],'')+''','''+ISNULL([CONST_TYPE],'')+''','''+ISNULL([COMP_ID],'')+''','''+ISNULL([VSIZE],'')+''','''+ISNULL([UOM_VSIZE],'')+''','''+ISNULL([VSPEC_TYPE],'')+''','''+ISNULL([VSPEC_NUM],'')+''','''+ISNULL([VPRESRATE],'')+''','''+ISNULL([VCONDITION],'')+''','''+ISNULL([PID_NO],'')+''','''+ISNULL([PROJ_STAT],'')+''')' FROM [VALVES]
DELETE FROM [VALVES]
--INSERT INTO [VALVES] VALUES ('90009-O','90-HV-801','90','HV','','801','','AT_HVALVE','NEW','559983967_20214','80','mm','VBA','001','','','90-AO5678','NEW')
INSERT INTO [VALVES] VALUES ('90009-O','90-HV-802','90','HV','','802','','AT_HVALVE','NEW','559983967_20223','80','mm','VBA','101','','','90-AO5678','NEW')
INSERT INTO [VALVES] VALUES ('90010-O','90-HV-803','91','HV','','803','','AT_HVALVE','NEW','559983967_24079','50','mm','VGA','001','','','90-AO5678','NEW')