/*
 * File: Scripts/AM/store/MappingStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.store.MappingStore', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'AM.model.MappingModel'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      autoLoad: true,
      storeId: 'MappingStore',
      model: 'AM.model.MappingModel',
      root: {
        type: 'MappingNode',
        expanded: true
      },
      proxy: {
        type: 'ajax',
        actionMethods: {
          read: 'POST'
        },
        extraParams: {
          type: 'MappingNode',
          id: null,
          range: null,
          graphName: null,
          contextName: null,
          endpoint: null,
          baseUrl: null
        },
        timeout: 600000,
        url: 'mapping/getnode',
        reader: {
          type: 'json'
        }
      }
    }, cfg)]);
  }
});