/*
 * File: Scripts/AM/view/menus/GraphMenu.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.menus.GraphMenu', {
  extend: 'Ext.menu.Menu',
  alias: 'widget.graphmenu',

  floating: true,
  width: 130,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'menuitem',
          action: 'refreshfacade',
          icon: 'Content/img/table_refresh.png',
          text: 'Refresh Facade'
        },
        {
          xtype: 'menuseparator'
        },
        {
          xtype: 'menuitem',
          action: 'editnewgraph',
          itemId: 'editgraph',
          icon: 'Content/img/16x16/document-properties.png',
          text: 'Edit GraphMap'
        },
        {
          xtype: 'menuitem',
          action: 'deletegraph',
          icon: 'Content/img/16x16/edit-delete.png',
          text: 'Delete GraphMap'
        },
        {
          xtype: 'menuseparator'
        },
        {
          xtype: 'menuitem',
          action: 'opengraph',
          icon: 'Content/img/16x16/mapping.png',
          text: 'Open GraphMap'
        }
      ]
    });

    me.callParent(arguments);
  }

});