/*
 * File: Scripts/AM/view/menus/RolemapMenu.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.menus.RolemapMenu', {
  extend: 'Ext.menu.Menu',
  alias: 'widget.rolemapmenu',

  width: 130,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'menuitem',
          action: 'addclassmap',
          icon: 'Content/img/16x16/document-new.png',
          text: 'Add ClassMap'
        },
        {
          xtype: 'menuitem',
          action: 'makepossessor',
          text: 'Make Possessor'
        },
        {
          xtype: 'menuitem',
          action: 'makereference',
          text: 'Make Reference'
        },
        {
          xtype: 'menuitem',
          action: 'mapproperty',
          text: 'Map Property'
        },
        {
          xtype: 'menuitem',
          action: 'mapvaluelist',
          text: 'Map ValueList'
        },
        {
          xtype: 'menuitem',
          action: 'resetmapping',
          text: 'Reset Mapping'
        }
      ]
    });

    me.callParent(arguments);
  }

});