/*
 * File: Scripts/AM/view/menus/ScopeMenu.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.menus.ScopeMenu', {
  extend: 'Ext.menu.Menu',
  alias: 'widget.scopemenu',

  floating: true,
  width: 130,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'menuitem',
          action: 'neweditscope',
          itemId: 'newfolder',
          icon: 'Content/img/16x16/document-new.png',
          text: 'New Folder'
        },
        {
          xtype: 'menuitem',
          action: 'neweditscope',
          itemId: 'editfolder',
          icon: 'Content/img/16x16/document-properties.png',
          text: 'Edit Folder'
        },
        {
          xtype: 'menuitem',
          action: 'deletescope',
          icon: 'Content/img/16x16/edit-delete.png',
          text: 'Delete Folder'
        },
        {
          xtype: 'menuseparator'
        },
        {
          xtype: 'menuitem',
          action: 'neweditendpoint',
          icon: 'Content/img/16x16/document-new.png',
          text: 'New Endpoint'
        }
      ]
    });

    me.callParent(arguments);
  }

});