/*
 * File: Scripts/AM/view/spreadsheet/SourceForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.spreadsheet.SourceForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.spreadsheetsourceform',

  bodyPadding: 10,
  bodyStyle: 'padding:10px 5px 0',
  method: 'POST',
  url: 'spreadsheet/upload',

  initComponent: function() {
    var me = this;

    me.initialConfig = Ext.apply({
      method: 'POST',
      url: 'spreadsheet/upload'
    }, me.initialConfig);

    Ext.applyIf(me, {
      defaults: {
        anchor: '100%',
        msgTarget: 'side'
      },
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'tbfill'
            },
            {
              xtype: 'button',
              action: 'uploadspreadsheet',
              iconCls: 'am-document-up',
              text: 'Upload'
            }
          ]
        }
      ],
      items: [
        {
          xtype: 'hiddenfield',
          name: 'context'
        },
        {
          xtype: 'hiddenfield',
          name: 'endpoint'
        },
        {
          xtype: 'hiddenfield',
          name: 'baseUrl'
        },
        {
          xtype: 'hiddenfield',
          name: 'datalayer'
        },
        {
          xtype: 'filefield',
          anchor: '100%',
          name: 'sourceFile',
          fieldLabel: 'Spreadsheet Source',
          labelWidth: 150,
          emptyText: 'Select a Spreadsheet',
          buttonConfig: {
            iconCls: 'upload-icon'
          },
          buttonOnly: false,
          buttonText: ''
        },
        {
          xtype: 'checkboxfield',
          anchor: '100%',
          name: 'generate',
          fieldLabel: 'Generate',
          hideLabel: false,
          labelWidth: 150,
          checked: true
        }
      ]
    });

    me.callParent(arguments);
  }

});