/*
 * File: Scripts/AM/view/common/PropertyPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.common.PropertyPanel', {
  extend: 'Ext.grid.property.Grid',
  alias: 'widget.propertypanel',

  border: true,
  frame: false,
  autoScroll: true,
  collapsed: false,
  collapsible: true,
  title: 'Details',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      viewConfig: {
        stripeRows: true
      },
      source: {
        
      }
    });

    me.callParent(arguments);
  }

});