/*
 * File: Scripts/AM/view/nhibernate/MultiSelectionGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.MultiSelectionGrid', {
  extend: 'Ext.grid.Panel',
  alias: 'widget.multiselectiongrid',

  maxHeight: 260,
  autoScroll: true,
  frameHeader: false,
  header: false,
  enableColumnHide: false,
  enableColumnMove: false,
  enableColumnResize: false,
  scroll: 'vertical',
  sortableColumns: false,
  store: 'MultiStore',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      viewConfig: {

      },
      selModel: Ext.create('Ext.selection.RowModel', {
        mode: 'MULTI'
      }),
      columns: [
        {
          xtype: 'gridcolumn',
          setText: function(text) {
            this.text = text;
          },
          width: 220,
          align: 'center',
          dataIndex: 'DisplayField',
          text: 'DisplayField'
        }
      ]
    });

    me.callParent(arguments);
  },

  loadItems: function(items) {
    var me = this;
    var store = me.getStore();
    store.removeAll();
    var records = [];

    Ext.each(items, function(item) {
      records.push({'DisplayField': item});
    });

    store.add(records);
  },

  selectItems: function(items) {
    var me = this;
    var sm = me.getSelectionModel();
    var selected = sm.getSelection();
    var store = me.getStore();
    sm.bindStore(store);
    var records = [];
    Ext.each(items, function(item) {
      var record = store.findRecord('DisplayField', item);
      if(record) {
        records.push(record); 
      }           
    });

    sm.select(records, true, true);



  },

  getSelectedItems: function() {
    var me = this;
    var store = me.getStore();
    var selectionModel = me.getSelectionModel();
    var items = [];

    Ext.each(selectionModel.getSelection(), function(record) {
      items.push(record.get('DisplayField'));
    });
  },

  getAllItemNames: function() {
    var me = this;
    var store = me.getStore();
    var items = [];
    var count = store.getCount();

  }

});