/*
 * File: Scripts/AM/view/nhibernate/NhibernatePanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.NhibernatePanel', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.nhibernatepanel',

  requires: [
    'AM.view.nhibernate.NhibernateTree'
  ],

  dirNode: '',
  treeNode: '',
  border: false,
  layout: {
    type: 'border'
  },
  closable: true,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'nhibernatetree',
          width: 280,
          flex: 1,
          floatable: false,
          region: 'center'
        },
        {
          xtype: 'container',
          flex: 2,
          floatable: false,
          region: 'east',
          split: true,
          itemId: 'nhibernateContent',
          width: 150,
          layout: {
            type: 'fit'
          }
        }
      ]
    });

    me.callParent(arguments);
  }

});