/*
 * File: Scripts/AM/view/menus/ApplicationMenu.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.menus.ApplicationMenu', {
  extend: 'Ext.menu.Menu',
  alias: 'widget.applicationmenu',

  floating: true,
  width: 140,
  minButtonWidth: 85,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'menuitem',
          action: 'neweditendpoint',
          itemId: 'editendpoint',
          icon: 'Content/img/16x16/document-properties.png',
          text: 'Edit Endpoint'
        },
        {
          xtype: 'menuitem',
          action: 'deleteendpoint',
          icon: 'Content/img/16x16/edit-delete.png',
          text: 'Delete Endpoint'
        },
        {
          xtype: 'menuseparator'
        },
        {
          xtype: 'menuitem',
          action: 'configureendpoint',
          icon: 'Content/img/16x16/preferences-system.png',
          text: 'Open Configuration'
        }
      ]
    });

    me.callParent(arguments);
  }

});