/*
 * File: Scripts/AM/view/directory/AvailBaseUrlCombo.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.directory.AvailBaseUrlCombo', {
  extend: 'Ext.form.field.ComboBox',
  alias: 'widget.availbaseurlcombo',

  fieldLabel: 'Base Url',
  selectOnFocus: false,
  displayField: 'baseurl',
  forceSelection: true,
  hiddenName: 'Urlocator',
  minChars: 100000,
  store: 'BaseUrlStore',
  typeAhead: false,
  valueField: 'baseurl',

  initComponent: function() {
    var me = this;

    me.callParent(arguments);
  }

});