/*
 * File: Scripts/AM/view/mapping/ClassMapForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.mapping.ClassMapForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.classmapform',

  mappingNode: '',
  parentClassId: '',
  formid: '',
  floating: false,
  bodyStyle: 'padding:10px 5px 0',
  method: 'POST',
  url: 'mapping/addclassmap',

  initComponent: function() {
    var me = this;

    me.initialConfig = Ext.apply({
      method: 'POST',
      url: 'mapping/addclassmap'
    }, me.initialConfig);

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'fieldset',
          hidden: true,
          items: [
            {
              xtype: 'hiddenfield',
              name: 'graphName'
            },
            {
              xtype: 'hiddenfield',
              name: 'index'
            },
            {
              xtype: 'hiddenfield',
              name: 'parentClassId'
            },
            {
              xtype: 'hiddenfield',
              name: 'roleName'
            },
            {
              xtype: 'hiddenfield',
              name: 'dataObject'
            },
            {
              xtype: 'hiddenfield',
              name: 'propertyName'
            },
            {
              xtype: 'hiddenfield',
              name: 'baseUrl'
            },
            {
              xtype: 'hiddenfield',
              name: 'endpoint'
            },
            {
              xtype: 'hiddenfield',
              name: 'contextName'
            },
            {
              xtype: 'hiddenfield',
              name: 'relation'
            },
            {
              xtype: 'hiddenfield',
              name: 'classID'
            },
            {
              xtype: 'hiddenfield',
              name: 'classLabel'
            },
            {
              xtype: 'hiddenfield',
              name: 'objectName'
            }
          ]
        },
        {
          xtype: 'container',
          anchor: '100%',
          html: 'Drop a Property Node here.',
          itemId: 'cmpcontainer',
          style: 'border:1px silver solid;margin:5px;padding:8px;height:40px',
          styleHtmlContent: true
        },
        {
          xtype: 'container',
          anchor: '100%',
          html: 'Drop a Class Node here.',
          itemId: 'cmccontainer',
          style: 'border:1px silver solid;margin:5px;padding:8px;height:40px',
          styleHtmlContent: true
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'bottom',
          items: [
            {
              xtype: 'tbfill'
            },
            {
              xtype: 'button',
              handler: function(button, event) {
                me.onSave();
              },
              text: 'Ok'
            },
            {
              xtype: 'button',
              handler: function(button, event) {
                me.onReset();
              },
              text: 'Cancel'
            }
          ]
        }
      ],
      listeners: {
        afterrender: {
          fn: me.onFormAfterRender,
          scope: me
        }
      }
    });

    me.callParent(arguments);
  },

  onFormAfterRender: function(abstractcomponent, options) {
    var me = this;
    var pcont = me.down('#cmpcontainer');
    var propertyDropTarget = new Ext.dd.DropTarget(pcont.getEl(),{
      scope: me,
      ddGroup: 'propertyGroup',
      copy: false,
      overClass: 'over',
      notifyOver: function(dragSource, event, data){
        if (data.records[0].data.type != 'DataPropertyNode' && data.records[0].data.type != 'KeyDataPropertyNode')
        return this.dropNotAllowed;
        else
        return this.dropAllowed;
      },
      notifyDrop: function(dragSource, event, data){
        if (data.records[0].data.type != 'DataPropertyNode' && data.records[0].data.type != 'KeyDataPropertyNode') {
          return false;
        }
        else {
          me.getForm().findField('objectName').setValue(data.records[0].data.id);
          me.getForm().findField('relation').setValue(data.records[0].data.property.Related);
          var msg = 'Property: ' + data.records[0].data.id.split('/')[data.records[0].data.id.split('/').length - 1];
          pcont.update(msg);
          return true;
        }
      },
      notifyEnter: function(dd, e, data) {
        if (data.records[0].data.type != 'DataPropertyNode' && data.records[0].data.type != 'KeyDataPropertyNode')
        return this.dropNotAllowed;
        else
        return this.dropAllowed;
      }
    });

    var ccont = me.down('#cmccontainer');
    var classDropTarget = new Ext.dd.DropTarget(ccont.getEl(),{
      scope: me,
      ddGroup: 'refdataGroup',
      copy: false,
      overClass: 'over',
      notifyEnter: function (dd, e, data) {
        if (data.records[0].data.type != 'ClassNode')
        return this.dropNotAllowed;
        else
        return this.dropAllowed;    
      },
      notifyOver: function(dragSource, event, data){
        if (data.records[0].data.type != 'ClassNode')
        return this.dropNotAllowed;
        else
        return this.dropAllowed;
      },
      notifyDrop: function(dragSource, event, data){
        if (data.records[0].data.type != 'ClassNode') {
          var message = 'Please slect a RDL Class...';
          showDialog(400, 100, 'Warning', message, Ext.Msg.OK, null);
          return false;
        }
        me.getForm().findField('classLabel').setValue(data.records[0].data.record.Label);
        me.getForm().findField('classUrl').setValue(data.records[0].data.record.Uri);
        var msg = 'Class Label: ' + data.records[0].data.record.Label;
        ccont.update(msg);
        return true;
      }
    });
  },

  onReset: function() {
    var me = this;
    var win = me.up('window');
    me.getForm().reset();
    win.destroy();
  },

  onSave: function() {
    var me = this;
    var message;
    if(me.getForm().isValid()) {
      me.submit({
        waitMsg: 'Saving Data...',
        success: function (f, a) {

          me.fireEvent('Save', me);
        },
        failure: function (f, a) {
          message = 'Failed to Add ClassMap to RoleMap';
          showDialog(400, 100, 'Warning', message, Ext.Msg.OK, null);
        }
      });
    } else {
      message = 'Form is not complete. Cannot save record.';
      showDialog(400, 100, 'Warning', message, Ext.Msg.OK, null);   
    }



  }

});