/*
 * File: Scripts/AM/store/SearchStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.store.SearchStore', {
  extend: 'Ext.data.TreeStore',

  requires: [
    'AM.model.SearchModel'
  ],

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      autoLoad: false,
      storeId: 'SearchStore',
      model: 'AM.model.SearchModel',
      root: {
        expanded: true
      },
      proxy: {
        type: 'ajax',
        actionMethods: {
          read: 'POST'
        },
        extraParams: {
          id: null,
          type: null,
          query: null,
          reset: null,
          limit: 100,
          start: 0
        },
        timeout: 600000,
        url: 'refdata/getnode',
        reader: {
          type: 'json'
        }
      }
    }, cfg)]);
  }
});