/*
 * File: Scripts/AM/view/common/CenterPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.common.CenterPanel', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.centerpanel',

  requires: [
    'AM.view.common.ContentPanel',
    'AM.view.search.SearchPanel'
  ],

  border: true,
  layout: {
    type: 'border'
  },
  collapsible: false,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'contentpanel',
          id: 'maincontent',
          region: 'center'
        },
        {
          xtype: 'searchpanel',
          region: 'south',
          split: true
        }
      ]
    });

    me.callParent(arguments);
  }

});