/*
 * File: Scripts/AM/view/spreadsheet/SpreadsheetPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.spreadsheet.SpreadsheetPanel', {
  extend: 'Ext.panel.Panel',
  alias: 'widget.spreadsheetpanel',

  requires: [
    'AM.view.spreadsheet.SpreadsheetTree',
    'AM.view.common.PropertyPanel'
  ],

  layout: {
    type: 'border'
  },
  closable: true,

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'spreadsheettree',
          region: 'center'
        },
        {
          xtype: 'propertypanel',
          width: 250,
          title: 'Spreadsheet Details',
          region: 'east',
          split: true
        }
      ]
    });

    me.callParent(arguments);
  }

});