/*
 * File: Scripts/AM/view/nhibernate/DataObjectForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.DataObjectForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.dataobjectform',

  disabled: false,
  defaultType: 'textfield',
  bodyStyle: 'background:#eee;padding:10px 0px 0px 10px',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      items: [
        {
          xtype: 'label',
          anchor: '100%',
          cls: 'x-form-item',
          style: 'font-weight:bold;',
          text: 'Data Object'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          disabled: true,
          saveDelay: 160,
          name: 'tableName',
          fieldLabel: 'Table Name',
          labelWidth: 160,
          allowBlank: false
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          disabled: false,
          saveDelay: 160,
          name: 'objectNamespace',
          fieldLabel: 'Object Namespace',
          labelWidth: 160,
          allowBlank: false
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          disabled: false,
          saveDelay: 160,
          name: 'objectName',
          fieldLabel: 'Object Name',
          labelWidth: 160,
          allowBlank: false,
          regex: /^[a-zA-Z_][a-zA-Z0-9_]*$/,
          regexText: '<b>Error</b></br>Invalid Value. A valid value should start with alphabet or "_", and follow by any number of "_", alphabet, or number characters'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          disabled: false,
          saveDelay: 160,
          name: 'keyDelimiter',
          fieldLabel: 'Key Delimiter',
          labelWidth: 160,
          allowBlank: false
        },
        {
          xtype: 'textareafield',
          anchor: '100%',
          height: 140,
          name: 'description',
          fieldLabel: 'Description',
          labelWidth: 160
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          layout: {
            padding: 4,
            type: 'hbox'
          },
          items: [
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              action: 'dataobjectformapply',
              iconCls: 'am-apply',
              text: 'Apply'
            },
            {
              xtype: 'tbspacer',
              width: 4
            },
            {
              xtype: 'button',
              action: 'dataobjectformreset',
              iconCls: 'am-edit-clear',
              text: 'Reset'
            }
          ]
        }
      ]
    });

    me.callParent(arguments);
  }

});