/*
 * File: Scripts/AM/view/nhibernate/RelationsForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.RelationsForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.relationsform',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      defaults: {
        labelWidth: 130,
        allowBlank: false
      },
      items: [
        {
          xtype: 'label',
          cls: 'x-form-item',
          style: 'font-weight:bold;',
          text: 'Add/Remove relationship'
        },
        {
          xtype: 'textfield',
          anchor: '100%',
          name: 'relationName',
          fieldLabel: 'Relationship Name',
          listeners: {
            keydown: {
              fn: me.onRelationKeydown,
              scope: me
            }
          }
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          layout: {
            padding: 4,
            type: 'hbox'
          },
          items: [
            {
              xtype: 'button',
              iconCls: 'am-apply',
              text: 'Apply',
              tooltip: 'Apply the current changes to the data objects tree'
            },
            {
              xtype: 'tbseparator',
              width: 4
            },
            {
              xtype: 'button',
              icon: 'Content/img/16x16/edit-clear.png',
              iconCls: 'am-edit-clear',
              text: 'Reset',
              tooltip: 'Reset to the latest applied changes'
            }
          ]
        }
      ]
    });

    me.callParent(arguments);
  },

  onRelationKeydown: function(textfield, e, options) {
    if (e.getKey() == e.ENTER) {
      //TODO addRelationship(me, node, contextName, endpoint);
    }
  }

});