/*
 * File: Scripts/AM/view/nhibernate/RelationsGrid.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AM.view.nhibernate.RelationsGrid', {
  extend: 'Ext.grid.Panel',
  alias: 'widget.relationsgrid',

  frame: false,
  store: 'RelationsStore',

  initComponent: function() {
    var me = this;

    Ext.applyIf(me, {
      viewConfig: {

      },
      columns: [
        {
          xtype: 'gridcolumn',
          dataIndex: 'relationName',
          flex: 1,
          text: 'Data Relationship Name'
        }
      ],
      dockedItems: [
        {
          xtype: 'toolbar',
          dock: 'top',
          items: [
            {
              xtype: 'tbseparator',
              width: 4
            },
            {
              xtype: 'button',
              iconCls: 'am-list-add',
              text: 'Add'
            },
            {
              xtype: 'tbseparator',
              width: 4
            },
            {
              xtype: 'button',
              iconCls: 'am-list-remove',
              text: 'Remove'
            }
          ]
        }
      ]
    });

    me.callParent(arguments);
  }

});